# hardware deploy env
name: deploy
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pytorch
  - pip
  - pip:
    - "mujoco>=3.5.0"
    - "warp-lang>=1.11.1"
    - onnx
    - onnxruntime
    - pygame
    - wandb
    - h5py
